### ISSUE TITLE
Missing Yugoslavia

### ISSUE THREAD

**Issue by badreddine-dlaila** [cosmos-loops/I18N#16]
Hello,

Seems that Yugoslavia is missing in Europe country list.
I can added if needed but I will need some help on Chinese translation :)

**Comment by alexinea** [comment]
Hi, @badreddine-dlaila ,

I searched for information about Yugoslavia, and I found that Yugoslavia became two independent countries in 2006:

- 1963-1992, Socialist Federal Republic of Yugoslavia
- 1992-2003, Federal Republic of Yugoslavia
- 2003-2006, State Union of Serbia and Montenegro
- 2006-present, independent as "Serbia" and "Montenegro"

Therefore, Yugoslavia has become a "historical country."

Can I know your reason for adding Yugoslavia?

In addition, for countries that "existed but have now become another country" and countries whose country names have changed, what form should we maintain and manage? Do we need to add a "former name" information set for each country?

Of course, if we can find a better way to manage the information of contemporary countries (such as the collection of national information after World War II), I would be happy to add Yugoslavia to the list of countries.

---

The information of Yugoslavia is as follows:

- `UNCode`: `38`
- `Alpha2Code`: `YU`
- `Alpha3Code`: `YUG`
- `Name`: `Yugoslavia`
- `ShorterForm`: `Socialist Federal Republic of Yugoslavia`
- `ChineseName`: `南斯拉夫联盟共和国`
- `ChineseShorterForm`: `南斯拉夫`

The value of `I18N_IDENTITY_CODE` can be `i18n_country_nansilafu` (or `i18n_country_nansilafu_2003`, if we include the former country in the list of countries).

**Comment by badreddine-dlaila** [comment]
Hello @alexinea,

I completely agree with you about the fact that Yugoslavia has become a historical country.  I did some researches about that and I was quite surprised about my poor geographical culture 😅.

Here is my use case : I'm developing and maintaining an enterprise solution that performs OCR and conformity controls on official documents (Identity cards, driving licence, residence permits etc.)
I therefore use Cosmos.I18N.Countries for conversion needs in terme of countries information (could be nationalities, document issue country etc.). The tool process millions of documents/week.

We monitor every single exception in the application and we have noticed that some of the documents sent to the API are either old document Issued by former Republic of Yugoslavia or th nationalities on the document are 'YUG -> Republic of Yugoslavia'.

Completely agree with your proposal about former name for historical country. May be just a boolean value indicating that the country is a historical one can be enough.

Let me know if you want me to give you a hand on the implementation, will be more then happy to help 😄

**Comment by alexinea** [comment]
Hi, @badreddine-dlaila ,

I agree with a simple bool value to mark whether a country is a historical  one. I will add Yugoslavia to the list of countries first. Then publish it to nuget so you can use it.

In the next refactoring, I plan to add an API similar to `bool TryGetCountryInfo (string xxxCode, int year, out CountryInfo countryInfo)`. When this country is not yet born or no longer exists in the specified year, it returns `false` (The corresponding version of `GetCountryInfo` throws an exception)

By the way, does `Republic of Yugoslavia` refer to` The Federal Republic of Yugoslavia`?

**Comment by badreddine-dlaila** [comment]
Oh yes it refers to Federal Republic of Yugoslavia.
Great idea about `TryGetCountryInfo`, more Dot Net friendly I think.
I'll make sure to report to you any other issue logged on my API (production Logs) 😉

**Comment by alexinea** [comment]
Thank you so much for your help.

I have released a version that includes Yugoslavia.

**Comment by badreddine-dlaila** [comment]
Awesome !!

Tested the new Nuget package. All Good for me 😃 
Closing this issue 👏 

Thank you so much.
